### ISSUE TITLE
Same control point is always selected

### ISSUE THREAD

**Issue by keenanwoodall** [SebLague/Path-Creator#1]
Here's a video of the bug: https://streamable.com/3yg6d

**Comment by SebLague** [comment]
I haven't been able to reproduce this bug, but I added some code that will hopefully prevent it from happening. I'm closing this for now, but if anyone is still able to reproduce, please let me know and I'll reopen.

**Comment by keenanwoodall** [comment]
The bug was pretty inconsistent, but I've been playing around with the new version for a few minutes and it's been working perfectly so far. As of now I'd call it fixed, but I'll add another comment if something changes. Thanks!
