### ISSUE TITLE
VertexPath does not contain a constructor that takes only one argument

### ISSUE THREAD

**Issue by EnriqueE** [SebLague/Path-Creator#113]
Documentation says, Generating a path: 
`VertexPath GeneratePath(Vector2[] points, bool closedPath)
   {
       // Create a closed, 2D bezier path from the supplied points array
       // These points are treated as anchors, which the path will pass through
       // The control points for the path will be generated automatically
       BezierPath bezierPath = new BezierPath(points, closedPath, PathSpace.xy);
       // Then create a vertex path from the bezier path, to be used for movement etc
       return new VertexPath(bezierPath);
   }`
But, the last line seems incorrect, VertexPath does not contain a constructor that takes only one argument.

**Comment by James-Millan** [comment]
I've had the same issue. I investigated the implementation of the VertexPath and the constructors appear  to have changed since this documentation was written.
