### ISSUE TITLE
Path is not displaying when selected

### ISSUE THREAD

**Issue by kkkkkom** [SebLague/Path-Creator#115]
Dear Sir/Madam,

Really need your help here. We downloaded the asset from unity store, and worked with it for one project, and really liked it. But recently, suddenly the path curve is not displaying in unity editor .. 

So it still displays the curve when "not selected", since the "display when not selected" option is turned on. But if I select the path object, it doesn't display the path anymore, no curve, no anchor, no normal, neither bezier path nor vertex path is displaying anything .. 

We tried a few things, but couldn't bring it back .. In the game mode, the path still works as expected (e.g. the target object still moves along the path). But the issue with editor is preventing us from manual editing of the path .. Please help, appreciate your time and help!

**Comment by SebLague** [comment]
Hello, do you have Gizmos disabled (in the top right above the scene view)?

**Comment by kkkkkom** [comment]
Thank you so much for prompt response! No, Gizmos are all enabled.

And we actually found the trigger. It seems it has a conflict with "FlatKit" (https://assetstore.unity.com/packages/vfx/shaders/flat-kit-toon-shading-and-water-143368)

More specifically, when we replace the render pipeline asset in the "Project Settings" under "Quality" tab with the flatkit pipeline asset, the issue happens. We are able to consistently reproduce this issue following this step.

The strange thing is that reverting pipeline asset back to default URP pipepline won't fix the issue, we have to first revert pipeline asset back, then completely remove the Flatkit to fix the issue ..

For now, we will just work with path creator first then add the flatkit as the last step. But I think It would be great help if you can root cause the issue and make it compatible with flatkit (although we can claim flatkit should be compatible with path creator as well :))
