### ISSUE TITLE
Add Meshcollider to RoadMeshCreator

### ISSUE THREAD

**Issue by NorthropBtwo** [SebLague/Path-Creator#12]
I added the option to add a Meshcollider to the RoadMeshCreator.

Problem: You could simply add a meshcollider in the Unity editor. But if you do that, the meshcollider does not get updated when the mesh is altered by changing the path. 

Solution: The skript attached takes care of updateing the meshcollider. Its very simple. Just enable the Meshcollider checkbox of the RoadMeshCreator Component.

I thought this feature could be intersing for others or even for trunk. 
[RoadMeshCreator.cs.zip](https://github.com/SebLague/Path-Creator/files/2825729/RoadMeshCreator.cs.zip)

**Comment by keenanwoodall** [comment]
Thanks for making this. 👍 
If you want it considered for addition to the repo, please make a pull request.
