### ISSUE TITLE
Vertex path doesn't update properly when new points are added in runtime

### ISSUE THREAD

**Issue by fartsniffer19** [SebLague/Path-Creator#124]
When adding new points to the Bezier path during runtime, the vertex path doesn't update unless you first click on the GameObject the PathCreator script is attached to.

**Comment by solomka121** [comment]
an event pathUpdate on PathCreator is running somehow in editor 
so , you should call method TriggerPathUpdate on PathCreator each time you change the bezzier path to trigget the event 
this way it should be working 😉

**Comment by fartsniffer19** [comment]
Thanks for the response! I actually ended up using VertexPathSettingsChanged on the PathCreatorData, which gets the vertex path again and calls TriggerPathUpdate. TriggerPathUpdate, for some reason, doesn't work when I call it by itself.

**Comment by ninjabou** [comment]
TriggerPathUpdate() does nothing for me as well, and frustratingly, VertexPathSettingsChanged does nothing as well! I feel as though I've tried everything, I'm just trying to change the positions of two of the points on the path using a script, but when the path isn't selected in the editor, it doesn't update. Please, any help would be appreciated, I'm at the end of my rope.
