### ISSUE TITLE
Getting constant NullReferenceException s in Unity 2022.2.10

### ISSUE THREAD

**Issue by HunterXZX** [SebLague/Path-Creator#130]
I've tried to add this to my project in Unity 2022.2.10 but as soon as I add the 'Path Creator' component to a blank object, the console gets flooded with errors and I don't see any of the expected path visuals/objects/gizmos.

I'm not smart enough to debug this, is it just not compatible with this version of Unity?

![image](https://user-images.githubusercontent.com/127504631/225176958-91f7ec3d-02a6-4f04-8839-1c51f3f93aa6.png)

**Comment by CaroRed** [comment]
I have the same problem, and I have the last version of the plugin. I'm using Unity 2022.1.12f1
