### ISSUE TITLE
PathCreator.pathUpdated not called in Editor

### ISSUE THREAD

**Issue by keenanwoodall** [SebLague/Path-Creator#14]
I'd love a callback in the editor when any spline properties/controls are changed.

**Comment by NorthropBtwo** [comment]
1. Add a script below the "Path creator" script which extends from PathSceneTool.
2. Overwrite the method PathUpdated().

Your script should look like this:

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MyUpdateEvent : PathCreation.Examples.PathSceneTool
{
    protected override void PathUpdated()
    {
        if (pathCreator != null)
        {
            Debug.Log("PathUpdated");
        }
    }
}
```
Please reply if that works for you.

**Comment by keenanwoodall** [comment]
I'm sure that works, but having to add some extra component just to be able to plug into the spline's update event is a bit messy. I'd end up with three components: `PathCreator`, "`PathUpdateEvent`", `SomeScriptThatNeedsUpdating`. I can't make `SomeScriptThatNeedsUpdating` inherit from `PathSceneTool` because it already inherits from another class. I think the best solution would be for the event, `pathUpdated` to just work in the editor?

**Comment by NorthropBtwo** [comment]
The pathUpdate works in edit mode. It is a bit tricky to subscribe to this event if you can not inherit from PathSceneTool. You said that SomeScriptThatNeedsUpdating inherts from another class. Can this other class inhert from  MonoBehaviour. If this is the case you can use the [ExecuteInEditMode] attribute. Just make sure that you add if(Application.IsPlaying(this)) in front of code that should not be called in edit mode.

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[ExecuteInEditMode]
public class MyUpdateEvent : MonoBehaviour
{
    PathCreation.PathCreator pathCreater;

    void OnEnable()
    {
        pathCreater = GetComponent<PathCreation.PathCreator>();
        if (pathCreater != null)
        {
            pathCreater.pathUpdated += PathCreater_pathUpdated;
        }
    }

    void OnDisable()
    {
        if (pathCreater != null)
        {
            pathCreater.pathUpdated -= PathCreater_pathUpdated;
            pathCreater = null;
        }
    }

    private void PathCreater_pathUpdated()
    {
        Debug.Log("PathUpdated");
    }

    private void Update()
    {
        if(Application.IsPlaying(this))
        {
            Debug.Log("Call Only while playing");
        }
    }
}
```

**Comment by keenanwoodall** [comment]
Got it working, thanks.
