### ISSUE TITLE
Playmaker Actions

### ISSUE THREAD

**Issue by dumbgamedev** [SebLague/Path-Creator#15]
Hi. 

Thanks for the great spline tool. I have had some request for playmaker actions, so I have gone ahead and started making some. You can find them here: https://github.com/dumbgamedev/Path-Creator-PlaymakerActions

They are released under the MIT license.

Could you add a link to your description page or documentation, so that more users can find them? 

Thank you :+1:

**Comment by keenanwoodall** [comment]
Thanks for making these! For now I won't be linking to the repo as I don't think external repos/extensions need to be referenced from the main package. I'm sure if people search for Path Creator Playmaker actions, they'll be able to find your repo 👍
