### ISSUE TITLE
Copying normal anchor angle value from another anchor

### ISSUE THREAD

**Issue by luvjungle** [SebLague/Path-Creator#16]
Hi. Thank for the asset.
I'have encountered an issue. When I try to set anchor angle to first point of my new BezierPath from the last point of previous Bezier Path, the angles appears to be mirrored.
Here is the angle of last point of Bezier 1
![default](https://user-images.githubusercontent.com/35488386/52342281-099e3d80-2a26-11e9-9c15-d1762fe0c470.png)
And here is the angle of first point of Bezier 2 after setting the value from Bezier 1 angle
![default](https://user-images.githubusercontent.com/35488386/52342325-2c305680-2a26-11e9-8b8c-4198e68e22a1.png)
My code is:

    path.bezierPath.SetAnchorNormalAngle(0, ZeroAngle());
    float ZeroAngle()
    {
        return prevPath.bezierPath.GetAnchorNormalAngle(prevPath.bezierPath.NumAnchorPoints - 1);
    }

Debug shows same values for angles.
Please help me with this issue.
Thank you.

**Comment by keenanwoodall** [comment]
Lemme make sure I understand the problem correctly -You set the start and end angle to the same value, but the normals don't line up where the path loops?

**Comment by keenanwoodall** [comment]
I'm gonna close this issue as there has been no response for two months.
