### ISSUE TITLE
Additional Example Scripts

### ISSUE THREAD

**Issue by dumbgamedev** [SebLague/Path-Creator#17]
Hi,

Here are three more example script that people may find helpful.

1. draws a line renderer according to the path
2. object spawner along the path.
3. set agent position according to percent, rather than by speed.

Thanks!
Eric

[ExampleScripts.zip](https://github.com/SebLague/Path-Creator/files/2839655/ExampleScripts.zip)

**Comment by keenanwoodall** [comment]
Thanks for making these 👍 
If you want them considered for the main repo please make a pull request.
