### ISSUE TITLE
Adding more than 5 point sometimes cause render error

### ISSUE THREAD

**Issue by lvnguyenmagmic** [SebLague/Path-Creator#18]
Hi, thanks for great assets, but I encounter an issue that when I adding more point it causing the mesh render error like the image. I use open path not a closed path. When this error is occur, I adding more point is useless the mesh is not updating anymore.

<img width="417" alt="screen shot 2019-02-14 at 9 36 54 am" src="https://user-images.githubusercontent.com/47019407/52758836-5abcbb80-303c-11e9-9f0d-ae7f85fe2958.png">
<img width="506" alt="screen shot 2019-02-14 at 9 38 07 am" src="https://user-images.githubusercontent.com/47019407/52758840-5d1f1580-303c-11e9-9e55-b5e4149ddc4c.png">

**Comment by keenanwoodall** [comment]
Are there any errors? What version of Unity of Unity are you using? Have you made any changes to the code?

**Comment by lvnguyenmagmic** [comment]
There is no error and I'm using Unity 2018.3.0f2 , I haven't change any code based , I just adjust setting in "Vertex Path" section , which is Max angle Error and Min Vertex Dst to 0.

**Comment by keenanwoodall** [comment]
Does it fix itself when you tweak the max dist/angle error?

**Comment by lvnguyenmagmic** [comment]
Yes it is.

**Comment by keenanwoodall** [comment]
Ok great, sounds like the problem was fixed.
