### ISSUE TITLE
Path Creator ignores its gameobject's transform changes

### ISSUE THREAD

**Issue by semihcihan** [SebLague/Path-Creator#2]
Once you create the path, it never gets updated with the changes made on the gamobject's tranform. Normally, I would expect the changes on the game object's or its parents' transform changes to affect the path itself too. So it would be better if the created path's points were relative to the game object.

I think the tool is almost perfect and thank you for sharing it.

**Comment by ben4d85** [comment]
I am experiencing the same issue as @semihcihan.

My suggestion would be to remove the "Enable Transforms" checkbox and instead have it behave like a _normal GameObject_ - i.e. support being able to change it's x,y,z via the Inspector (expected Unity behaviour).

**Comment by DDru** [comment]
@ben4d85, the path is not updated in realtime. You can't attach path to some object.

**Comment by SebLague** [comment]
I can easily make the transform position affect the path, but with the way I'm currently handling rotation and scaling, I can't use the transform's values for those. Not sure if its better to implement only transform position, or to be consistent and not use any values from the transform...

**Comment by DDru** [comment]
Can make two components? One for static and the other for realtime.

**Comment by keenanwoodall** [comment]
Gonna close this for now as having two scripts isn't different currently feasible. It may be possible to get it to work relative to the transform at some point, but right now it presents some seriously technical problems.
