### ISSUE TITLE
Add speed modifier to path points

### ISSUE THREAD

**Issue by Gabryxx7** [SebLague/Path-Creator#22]
First of all, thanks for the wonderful work, I am definitely gonna use it in the future even just to see these smooth movements maybe with a particle system.

Just some suggestions on some improvements:

- It would be cool if every points would have a certain speed modifier, so that the object could slow down or get faster the closer it is to the node. The speed could be interpolated between one node and the next one and a weight of each node's speed could tell how strong is the acceleration/deceleration to that point.
- Another way of doing this would be some sort of speed modulation according to how steep a hill his (on the x-y plane) or how tight the curve is (on x-z plane). For instance, a curve would force the object to slow down, and this is given by how curved the path is a that point given the angular velocity (just like you would slow down while driving on a very tight turn). This is could be achieved by using the same idea as before, each point would get a speed modifier, but this time would be computed according to the curve between one point and the next one. The sampling rate (angle error in the vertex path) would give different results obviously but it would allow for a single modular implementation of the path's points speed.

Other suggestions on it would be any kind of parameter that can be interpolated like color, materials, scale.

**Comment by keenanwoodall** [comment]
Integrating all of these properties directly into the Path Creator component would add unnecessary overhead for everyone who doesn't use the features. However, there's no reason you cannot make these effects externally.

To demonstrate my point, I wrote a quick variant of the `PathFollower` script that lets you use an Animation Curve to map the speed along the path.

![2019-03-27_01-22-27](https://user-images.githubusercontent.com/9631530/55054881-4acacb00-502f-11e9-9fcc-f7608436caa7.gif)
```cs
using UnityEngine;
using PathCreation;

public class AdvancedPathFollower : MonoBehaviour
{
	public float speed = 5;
	public EndOfPathInstruction loopMode = EndOfPathInstruction.Loop;
	public AnimationCurve speedAlongPath = AnimationCurve.EaseInOut (0f, 1f, 1f, 0.1f);
	[Space]
	public PathCreator pathCreator;

	private float distance;

	private void Update ()
	{
		var path = pathCreator.path;

		// Get the normalized distance along the path (in a 0 to 1 range)
		var t = (distance % path.length) / path.length;
		// Get the new speed from the curve
		var curveSpeed = speedAlongPath.Evaluate (t);
		// Move based on the global speed multiplied by the speed sampled from the curve
		distance += speed * curveSpeed * Time.deltaTime;

		transform.SetPositionAndRotation (path.GetPointAtDistance (distance, loopMode), path.GetRotationAtDistance (distance, loopMode));
	}
}
```

By changing where/how you sample points from the path you can create pretty much any effect!
