### ISSUE TITLE
Branching and Merging [Proposal]

### ISSUE THREAD

**Issue by aekoch** [SebLague/Path-Creator#25]
Hi there Seb and Keenan, 

The ability to create a new path attached to an old path (branch) and join an existing path (merge) would be a really cool feature that would add a lot of value to this package.  It could easily turn into an implementation nightmare if not properly constrained, but I think I have an approach that is simple enough to avoid increasing the complexity too much.  I've already forked the project, and am working on implementing this now.  This issue serves both as a design document and a request for feedback on the proposed additions.

A branch can be achieved manually by creating a new path and copying anchor/control pair from the original path into the first anchor/control pair for the new path.  Similarly, a merge can be achieved by doing the same with the last anchor/control pair.  Here's an example of the result.

Original Path: 
![BranchingPaths2](https://user-images.githubusercontent.com/14917288/56087264-e41a1f80-5e2c-11e9-86da-716e170214ea.PNG)
Branching and Merging path:
![BranchingPaths1](https://user-images.githubusercontent.com/14917288/56087265-ebd9c400-5e2c-11e9-8a31-514304fb45ab.PNG)

The manual approach could be automated by allowing an anchor on one curve to reference an anchor on a different curve by providing the PathCreator and the index of the target anchor.  Each anchor can only reference one other anchor (one parent), but each anchor might be the target of many references (many children).  Each BezierPath now needs to keep track of each anchor's parent and children.  Control points do not need to be kept track of like this because they are referenced implicitly by the anchors.

```c#
List<Tuple<BezierPath, int>> anchorsParent;
List<List<Tuple<BezierPath, int>>> anchorsChildren;
```

It would also be good to keep track of the relationships between BezierPaths:
```c#
Dictionary<BezierPath, Hashset<int>> pathIsParentAtAnchor;
Dictionary<BezierPath, Hashset<int>> pathIsChildAtAnchor;
```

One potential problem with this approach is that anchor indexes are not guaranteed to stay constant.  Each child anchor needs to know when its parent path adds, splits, or removes a segment.  Each parent anchor also needs to know when each child adds, splits, or removes a segment.  

```c#
public event System.Action<BezierPath, int> OnAnchorAdded;
public event System.Action<BezierPath, int> OnAnchorRemoved;
```

When either of these events is triggered, the receiver should ensure that they they are referencing the same anchor they were before the event, or that they remove the reference if the anchor was removed.  Changes can occur in one of three locations: upstream, downstream, or on each referenced index. An event downstream (higher index) of an anchor will not affect the anchor index and an event downstream (lower index) of an anchor will offset the anchor index by one. If an addition event coincides with a referenced anchor, increment its index.  If a removal event coincides with a referenced anchor then remove all of the references to it.

**Comment by keenanwoodall** [comment]
I agree, path branching would be pretty awesome. I don't currently have the time to work on this, but if you come up with something that integrates elegantly within the greater system feel free to make a pull request and I'll take a look 👍

**Comment by aekoch** [comment]
Pull request submitted.  I'll close this issue.
