### ISSUE TITLE
Position Type-In for Path Points

### ISSUE THREAD

**Issue by Ziflin** [SebLague/Path-Creator#27]
I was curious if there were any plans to support manual type-in of path point positions? Specifically the start and end points for several paths we're using need to be set to a specific value.

**Comment by keenanwoodall** [comment]
This feature was already pushed a few months ago. The selected point has property fields drawn for its position and angle in the inspector. If you haven't recently, try pulling the latest revision and let me know if it works for you 👍

**Comment by Ziflin** [comment]
Hi @keenanwoodall, Yeah, it's there in the latest. It looks like the position value is in world-space though and we need it to be in local space. I may can fix this in a bit.

Also, was there an option to draw the starting point (t=0) in a different color. It's hard for us to tell which is 0 and which is 1.

**Comment by keenanwoodall** [comment]
Control points are stored in worldspace, but I'll look into displaying them as local points.

**Comment by SebLague** [comment]
Control points are now stored in local space.
