### ISSUE TITLE
Paths are always in world space?

### ISSUE THREAD

**Issue by Ziflin** [SebLague/Path-Creator#28]
It appears that moving a GameObject parent containing GameObject with a path has no affect on the path. Are there any plans to fix this or is there a work-around? For procedurally generated levels or placing paths in prefabs, this seems like a big problem.

**Comment by harrisyu** [comment]
Yes, I meet the same problem too... I use path creator in prefabs too, path just don't transform in parent space.

**Comment by Rabbodirect** [comment]
I'd also love the paths to work in local space rather than world space! I want to be able create a prefab with a path, and then move and rotate them in the level. It's such an excellent path creator system so far though :)

**Comment by SebLague** [comment]
This should be working now! Please let me know if you have any issues with it.
