### ISSUE TITLE
Not Recognized as a Unity Project

### ISSUE THREAD

**Issue by Dustin-Boyle** [SebLague/Path-Creator#4]
Hi, When I try to open the folder is not recognized as a Unity Project. Unity Version 2018.3.3

**Comment by RassBano** [comment]
Well thats probably because the the Folder is not a Unity Project. 
Its meant to be added to your Unity Project. If you just Drag & Drop the "PathCreator" Folder into the Project Window of an already opened Unity Project, then you are good to go
