### ISSUE TITLE
GetClosestPreviousPointIndexOnPath Function take alot of computation power

### ISSUE THREAD

**Issue by marcozakaria** [SebLague/Path-Creator#40]
![Capture](https://user-images.githubusercontent.com/24639480/65242999-b75aea00-dae7-11e9-9e6b-ab9025ff192b.PNG)

Hello, Thank you very mush for your amazing tutorials.
I am building a racing game and i am using these function to check if player is moving backward or not it works perfectly, but it is very heavy on computation.
Thanks.

**Comment by apautrot** [comment]
Yes looks like MathUtility started to be written with static cached data optimization in mind, but only half way, and this makes the code weird and suboptimal atm.

**Comment by kaninhot004** [comment]
Hope someone can optimize this.

**Comment by pschraut** [comment]
I've created a pull request #53, that contains optimization of that method.

**Comment by SebLague** [comment]
I've accepted pschraut's pull request
