### ISSUE TITLE
Change from one path to another

### ISSUE THREAD

**Issue by FrancisBru** [SebLague/Path-Creator#44]
Hello everyone,

I face a problem while I try to make my game object switch from one path to another using BoxCollider.

Here is some of the code 

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using PathCreation;

public class LandingOver : MonoBehaviour
{

    public PathCreator Path2;

    //Before this, my gameObject is following another path, let's call it Path1.
    void OnTriggerEnter(Collider other)
    {

        other.gameObject.GetComponent<Follower>().pathCreator = Path2;
        other.gameObject.GetComponent<Follower>().speed = 2f;

    }

}

Unfortunately the gameObject switch from Path1 to Path2 but begin from the middle of Path2, not from the begining. So the transition is a fail. How to prevent my gameObject to "jump" ignoring a large part of Path2 ?

Do you have any other method to suggest ?

Thank you in advance for your time and consideration,

Francis

**Comment by kaninhot004** [comment]
Try to stack 2nd path to end point of 1st path like this.
![image](https://user-images.githubusercontent.com/9493525/71456456-0b9ef580-27cc-11ea-90de-a7639aba334e.png)
![image](https://user-images.githubusercontent.com/9493525/71456464-10fc4000-27cc-11ea-949e-a24cd7f90381.png)

- Some path you need to made some distance *longer* for let scripts calculate.

- Sometimes you need to set distance to 0 after changing path *when it's out of control*.

**Comment by ShaneYu** [comment]
You could generate a path from the current position of the follower to the start of the new path, follow that until the end and then start the new (second) path. You can check if the follower has reached the end of the path by checking the transform.position is equal to the last point in the path.

**Comment by FrancisBru** [comment]
Hi everybody,

I tried the solutions suggested above.

Unfortunately, every time the GameObject is set on the new path, it starts from a certain distance from the begining of the path.

I tried to force the position with a transform.position, but it didn't work properly. It is like if the follower has a priority and does not care my attempts to set a position.

Here are some documents so you see what I face.

![Capture d’écran 2021-03-12 à 16 13 04](https://user-images.githubusercontent.com/57144666/110964698-bfe65680-8353-11eb-8956-500ca9109021.png)

https://user-images.githubusercontent.com/57144666/110964579-9d543d80-8353-11eb-902e-f2e08ac2c9ea.mp4


https://user-images.githubusercontent.com/57144666/110964644-b0670d80-8353-11eb-85c6-4a3248893263.mp4


I just want to switch from path1 to path2 smoothly, as in the second video (where I cheated because it is only one long path).

To be honest I managed to develop a solution, but it is ridiculously complicated :

- path2 overlap the end of path1
- GameObject is copied and a "ghost twin" is created on path 2 with a superior speed
- as soon as the distance between the twin and the original is less than 0.001f, the twin is made visible, and the original deleted

Does anybody has a simple solution for this or should I look into other assets ?

Thank you for your time and consideration,

Francis

**Comment by kaninhot004** [comment]
@FrancisBru In you case, I prefer add simple script to move between end pos 1 move to start pos 2 that's all.

**Comment by FrancisBru** [comment]
Hello Kanin,

Thank you for your answer !

Do you have any example of such a script ?

(I tried to force the position with "Path2.GetComponent<PathCreator>().path.GetPointAtDistance(0.0f, EndOfPathInstruction.Loop)", but I did not manage to do anything.)

Have a nice day,

Francis

**Comment by FrancisBru** [comment]
Topic closed.

1) Made the "distanceTravelled" variable from "Follower" class public.

2) Set "distanceTravelled" to "0.0f" after changing path.

Thank you everyone for participating.
