### ISSUE TITLE
Coordinates of Points in Inspector [Improvement]

### ISSUE THREAD

**Issue by ben4d85** [SebLague/Path-Creator#6]
As is, when I click on a point, I have no way of knowing its coordinates.

Could this be integrated with the Unity Inspector, so that these points can be moved around by changing the x, y, z coordinates in the Inspector (just like one can for everything else in Unity)?

**Comment by 2ndReality** [comment]
I found out that this was added in the develop branch.

**Comment by SebLague** [comment]
This has now been added to the main branch. Clicking on a point will now bring up a vector3 field in the inspector. (Thanks to Keenan)
