### ISSUE TITLE
VertexPath.GetPointAtTime(1.0f) return wrong answer

### ISSUE THREAD

**Issue by Orabig** [SebLague/Path-Creator#65]
VertexPath.GetPointAtTime(1.0f) returns the start of the path instead of the end
while VertexPath.GetPointAtTime(0.9999f) is working correctly, and returns a point which is very near to the end of the curve.

I have the same result with VertexPath.GetPointAtDistance(VertexPath.length) which is not working either.

**Comment by vadersb** [comment]
Hi! It is correct behavior, because by default VertexPath.GetPointAtTime() second argument is equal to EndOfPathInstruction.Loop, so it goes back to 0.0f when 1.0f is passed. Try calling VertexPath.GetPointAtTime(1.0f, EndOfPathInstruction.Stop)

**Comment by Orabig** [comment]
Many thanks for the very clear explanation.
