### ISSUE TITLE
Thicker Lines [Improvement]

### ISSUE THREAD

**Issue by ben4d85** [SebLague/Path-Creator#7]
Could you add an option to make the lines thicker, especially the normals? 

As is, they are almost invisible when zoomed even slightly out.

PS: I am asking for thickness, not length (which you already have).

**Comment by SebLague** [comment]
Tried using AAPolyLine, but it didn't look so good. Not aware of any other way to achieve, so closing for now.

**Comment by aekoch** [comment]
You can use DrawSolidRectangleWithOutline to draw a quad.  Replace the Handles.Drawline() call in Draw normals section of DrawBezierPathSceneEditor() with the following code

```c#
Vector3 prevVertex = normalsVertexPath.vertices[Mathf.Max(0, i - 1)];
Vector3 nextVertex = normalsVertexPath.vertices[Mathf.Min(normalsVertexPath.NumVertices - 1, i + 1)];
Vector3 forward = prevVertex - nextVertex; 
forward *= 0.02f; //Controls width - should be turned into a globalDisplaySettings variable

Vector3[] points = new Vector3[4];
points[0] = normalsVertexPath.vertices[i] - forward * 0.5f;
points[1] = points[0] + normalsVertexPath.normals[i] * globalDisplaySettings.normalsLength;
points[2] = points[1] + forward;
points[3] = points[0] + forward;
Handles.DrawSolidRectangleWithOutline(points, globalDisplaySettings.normals, globalDisplaySettings.normals);
```
